Repository kopia/kopia, pull requests merged in 2020-03, with the labels that each got.

#358 cli: allow override of snapshot start time and end time
  cli/command_snapshot_create.go
  tests/end_to_end_test/snapshot_create_test.go
Labels: enhancement

#369 object: added AsyncWrites to ObjectWriter, which improves performance…
  repo/object/object_manager.go
  repo/object/object_manager_test.go
  repo/object/object_writer.go
  snapshot/snapshotfs/upload.go
Labels: performance

#373 Support for gather writes, where blob.Storage.PutBlob gets a list of slices and writes them sequentially
  Makefile
  cli/command_repository_repair.go
  internal/blobtesting/concurrent.go
  internal/blobtesting/faulty.go
  internal/blobtesting/map.go
  internal/blobtesting/verify.go
  internal/gather/gather_bytes.go
  internal/gather/gather_bytes_test.go
  internal/gather/gather_write_buffer.go
  internal/gather/gather_write_buffer_chunk.go
  internal/gather/gather_write_buffer_chunk_test.go
  internal/gather/gather_write_buffer_test.go
  repo/blob/azure/azure_storage.go
  repo/blob/filesystem/filesystem_storage.go
  repo/blob/filesystem/filesystem_storage_test.go
  repo/blob/gcs/gcs_storage.go
  repo/blob/logging/logging_storage.go
  repo/blob/s3/s3_storage.go
  repo/blob/sftp/sftp_storage.go
  repo/blob/sharded/sharded.go
  repo/blob/storage.go
  repo/blob/storage_test.go
  repo/blob/webdav/webdav_storage.go
  repo/content/content_cache.go
  repo/content/content_cache_test.go
  repo/content/content_index_recovery.go
  repo/content/content_manager.go
  repo/content/content_manager_lock_free.go
  repo/format_block.go
  repo/format_block_test.go
Labels: enhancement, performance, provider
