Repository kopia/kopia, pull requests merged in 2023-08, with the labels that each got.

#3192 fix(repository): Storage config blob caching
  repo/format/format_manager_test.go
  repo/format/format_set_parameters.go
Labels: bug

#3131 feat(providers): support for auth with Azure AD
  cli/storage_azure.go
  go.mod
  go.sum
  repo/blob/azure/azure_options.go
  repo/blob/azure/azure_storage.go
  repo/blob/azure/azure_storage_test.go
Labels: enhancement, provider, enterprise, keep-open

#3220 test(repository): More precise check for retention in tests
  internal/blobtesting/object_locking_map.go
  internal/blobtesting/storage.go
  repo/blob/storage_extend_test.go
  repo/format/format_manager_test.go
  repo/maintenance/blob_retain_test.go
Labels: code-quality, test-coverage

#3241 refactor(providers): Create default provider that has common functions
  internal/blobtesting/map.go
  internal/blobtesting/object_locking_map.go
  repo/blob/azure/azure_storage.go
  repo/blob/b2/b2_storage.go
  repo/blob/filesystem/filesystem_storage.go
  repo/blob/gcs/gcs_storage.go
  repo/blob/gdrive/gdrive_storage.go
  repo/blob/readonly/readonly_storage.go
  repo/blob/s3/s3_storage.go
  repo/blob/sftp/sftp_storage.go
  repo/blob/sharded/sharded.go
  repo/blob/storage.go
  repo/blob/webdav/webdav_storage.go
Labels: provider, code-quality

#3225 fix(repository): skip epoch compaction and advancement on read-only storage
  internal/epoch/epoch_manager.go
  internal/epoch/epoch_manager_test.go
Labels: bug, robustness

#3226 fix(repository): Disable manifest manager compaction when in read-only mode
  repo/content/committed_read_manager.go
  repo/manifest/committed_manifest_manager.go
  repo/manifest/manifest_manager.go
  repo/manifest/manifest_manager_test.go
Labels: bug

#3244 refactor(repository): Add options struct to test helper
  repo/manifest/manifest_manager_test.go
Labels: code-quality
