Repository kopia/kopia, pull requests merged in 2023-04, with the labels that each got.

#2820 build(deps): bump minimist from 1.2.7 to 1.2.8 in /app
  app/package-lock.json
  app/package.json
Labels: dependencies, javascript

#2901 build(deps): upgrade github.com/hashicorp/golang-lru to 0.6.0
  go.mod
  go.sum
Labels: dependencies, go

#2910 build(infra): fix minio's mc installation
  tools/tools.mk
Labels: test-failure, project-infrastructure

#2920 fix(deps-dev): fixup mutex for make check-locks
  internal/blobtesting/faulty.go
  internal/fault/fault_set.go
Labels: bug, code-quality

#2956 feat(repository): Reduce memory usage when parsing manifests
  repo/manifest/committed_manifest_manager.go
  repo/manifest/serialized.go
  repo/manifest/serialized_test.go
  repo/manifest/testdata/manifests.go
Labels: performance
