Repository kopia/kopia, pull requests merged in 2024-03, with the labels that each got.

#3710 fix(deps): upgrade google.golang.org/protobuf to v1.33.0
  go.mod
  go.sum
Labels: dependencies, go, security

#3748 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#3651 refactor(general): perform index compaction during repo maintenance
  repo/maintenance/maintenance_run.go
Labels: performance, enterprise, resource-utilization
