Repository kopia/kopia, pull requests merged in 2025-04, with the labels that each got.

#4487 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4499 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4504 fix(general): `tempfile.Create` on Linux (x64/arm64)
  internal/tempfile/tempfile_linux.go
  internal/tempfile/tempfile_test.go
Labels: performance, resource-utilization

#4505 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4535 feat(providers): client certificate authentication for Azure Blob
  cli/storage_azure.go
  repo/blob/azure/azure_options.go
  repo/blob/azure/azure_storage.go
  repo/blob/azure/azure_storage_test.go
Labels: provider, security
