Repository kopia/kopia, pull requests merged in 2025-06, with the labels that each got.

#4625 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4626 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4627 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4629 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4630 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4635 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4636 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4637 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4641 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4642 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4648 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4656 chore(ci): upgrade Go toolchain to 1.23.10
  go.mod
Labels: dependencies, go, security

#4657 chore(ci): pin actions
  .github/workflows/auto-merge.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/dependency-review.yml
Labels: project-infrastructure, dependencies, security, github_actions

#4691 fix(general): migrate remnant piece to `crypto/hkdf`
  repo/encryption/encryption.go
Labels: dependencies, go, security
