Repository kopia/kopia, pull requests merged in 2025-05, with the labels that each got.

#4541 refactor(cli): cleanup `cli.repositoryAccessMode`
  cli/app.go
Labels: code-quality

#4551 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4565 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
  tests/htmlui_e2e_test/htmlui_e2e_test.go
Labels: htmlui-update

#4566 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4568 chore(ci): upgrade Go toolchain to 1.23.9
  go.mod
Labels: dependencies, go, security

#4574 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4575 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4577 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4587 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4596 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4597 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4620 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update
