Repository kopia/kopia, pull requests merged in 2025-01, with the labels that each got.

#4354 build(deps): upgrade grpc and opentelemetry dependencies
  go.mod
  go.sum
Labels: dependencies, go

#4360 build(deps): github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
  go.mod
  go.sum
Labels: dependencies, go

#4361 build(deps): bump docker/setup-qemu-action
  .github/workflows/make.yml
Labels: dependencies, github_actions

#4362 build(deps): bump codecov/codecov-action to 5.2.0
  .github/workflows/code-coverage.yml
Labels: dependencies, github_actions

#4364 build(deps): bump the github-actions group
  .github/workflows/code-coverage.yml
  .github/workflows/compat-test.yml
  .github/workflows/endurance-test.yml
  .github/workflows/htmlui-tests.yml
  .github/workflows/license-check.yml
  .github/workflows/lint.yml
  .github/workflows/make.yml
  .github/workflows/ossf-scorecard.yml
  .github/workflows/providers-core.yml
  .github/workflows/providers-extra.yml
  .github/workflows/race-detector.yml
  .github/workflows/stale.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests.yml
  .github/workflows/volume-shadow-copy-test.yml
Labels: dependencies, github_actions

#4248 chore(ci): upgrade Go to 1.23
  go.mod
  site/.go-version
  tools/tools.mk
Labels: breaking-change, dependencies, go

#4365 build(deps): bump google.golang.org/grpc
  go.mod
  go.sum
Labels: dependencies, go
