Repository kopia/kopia, pull requests merged in 2025-09, with the labels that each got.

#4806 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4824 feat(ui): upgraded htmlui to the latest version
  go.mod
  go.sum
Labels: htmlui-update

#4829 docs(general): correct terminology
  README.md
  site/content/docs/FAQs/_index.md
  site/content/docs/Features/_index.md
  site/content/docs/Getting started/_index.md
  site/content/docs/Repositories/_index.md
  site/content/docs/_index.md
Labels: documentation

#4833 build(deps): bump github.com/Azure/azure-sdk-for-go/sdk/azidentity
  go.mod
  go.sum
Labels: provider, dependencies, go
